"""
This module contains in-memory vehicle data. We will
replace this with a database in the future.
"""

VEHICLES: list[dict] = [
    {
        "id": "1",
        "make": "Tesla",
        "model": "Model 3",
        "year": 2024,
        "trim": "Long Range RWD",
        "colour": "Pearl White",
        "range_miles": 390,
        "battery_size_kwh": 82,
        "image_url": "https://example.com/images/tesla-model-3.jpg",
        "available": True,
    },
    {
        "id": "2",
        "make": "Tesla",
        "model": "Model Y",
        "year": 2024,
        "trim": "Long Range AWD",
        "colour": "Midnight Silver",
        "range_miles": 331,
        "battery_size_kwh": 82,
        "image_url": "https://example.com/images/tesla-model-y.jpg",
        "available": True,
    },
    {
        "id": "3",
        "make": "BMW",
        "model": "i4",
        "year": 2024,
        "trim": "eDrive40",
        "colour": "Skyscraper Grey",
        "range_miles": 367,
        "battery_size_kwh": 83.9,
        "image_url": "https://example.com/images/bmw-i4.jpg",
        "available": True,
    },
    {
        "id": "4",
        "make": "Volkswagen",
        "model": "ID.4",
        "year": 2024,
        "trim": "Pro Performance",
        "colour": "Dusk Blue",
        "range_miles": 283,
        "battery_size_kwh": 82,
        "image_url": "https://example.com/images/vw-id4.jpg",
        "available": False,
    },
    {
        "id": "5",
        "make": "Hyundai",
        "model": "IONIQ 6",
        "year": 2024,
        "trim": "Standard Range RWD",
        "colour": "Gravity Gold",
        "range_miles": 338,
        "battery_size_kwh": 77.4,
        "image_url": "https://example.com/images/hyundai-ioniq6.jpg",
        "available": True,
    },
    {
        "id": "6",
        "make": "Polestar",
        "model": "2",
        "year": 2024,
        "trim": "Long Range Single Motor",
        "colour": "Snow",
        "range_miles": 320,
        "battery_size_kwh": 82,
        "image_url": "https://example.com/images/polestar-2.jpg",
        "available": True,
    },
    {
        "id": "7",
        "make": "Kia",
        "model": "EV6",
        "year": 2024,
        "trim": "GT-Line AWD",
        "colour": "Runway Red",
        "range_miles": 310,
        "battery_size_kwh": 77.4,
        "image_url": "https://example.com/images/kia-ev6.jpg",
        "available": False,
    },
    {
        "id": "8",
        "make": "Mercedes-Benz",
        "model": "EQA",
        "year": 2024,
        "trim": "250+",
        "colour": "Polar White",
        "range_miles": 323,
        "battery_size_kwh": 70.5,
        "image_url": "https://example.com/images/mercedes-eqa.jpg",
        "available": True,
    },
    {
        "id": "9",
        "make": "Audi",
        "model": "Q4 e-tron",
        "year": 2024,
        "trim": "45 quattro",
        "colour": "Mythos Black",
        "range_miles": 298,
        "battery_size_kwh": 82,
        "image_url": "https://example.com/images/audi-q4-etron.jpg",
        "available": True,
    },
    {
        "id": "10",
        "make": "Nissan",
        "model": "Ariya",
        "year": 2024,
        "trim": "87kWh Evolve+",
        "colour": "Akatsuki Copper",
        "range_miles": 329,
        "battery_size_kwh": 87,
        "image_url": "https://example.com/images/nissan-ariya.jpg",
        "available": True,
    },
]
